spring.application.name=shipmentservice
server.port=8082

# Kafka Broker server
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Deserializer lib for Kafka Consumer (shipment service service)
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# By default, Spring Kafka uses BATCH mode -> auto acknowledge -> no retry. So, @RetryableTopic couldn't intervene in time -> endless loop
# Spring no longer performs the confirmation itself, but instead delegates that authority to @RetryableTopic -> control retry thread -> DLT topic
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

# Set 'partition 0' to store event for consumer in the first launch
spring.kafka.consumer.auto-offset-reset=earliest

# MySQL DataSource
spring.datasource.url=${SHIPMENT_DATASOURCE_URL:jdbc:mysql://localhost:3306/shipment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Shipment Business Logic
shipment.processing-days=2
shipment.shipping-days=3