spring.application.name=emailservice
server.port=8081

# Kafka Broker server
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Deserializer lib for Kafka Consumer (emailservice service)
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Serializer lib to send FAILED events to DLT Topic
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# By default, Spring Kafka uses BATCH mode -> auto acknowledge -> no retry. So, @RetryableTopic couldn't intervene in time -> endless loop
# Spring no longer performs the confirmation itself, but instead delegates that authority to @RetryableTopic -> control retry thread -> DLT topic
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

# Set 'partition 0' to store event for consumer in the first launch
spring.kafka.consumer.auto-offset-reset=earliest

# Email server (spring-boot-starter-mail)
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=hanhuynh.mailserver@gmail.com
#Create your app password with other (custom name)
#https://myaccount.google.com/u/1/apppasswords
spring.mail.password=apdh ukqm yfta glse

spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# MySQL DataSource
spring.datasource.url=${EMAIL_DATASOURCE_URL:jdbc:mysql://localhost:3306/email_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect