spring.application.name=orderservice
server.port=8080

# Kafka Broker server
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Serializer lib for Kafka Producer (account service)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Acks (feedback sucess for fail)
# 0:  no waiting Kafka broker response
# 1:  wait for partition leader writing events successfully, no wait for followers
# -1: wait for partition leader and followers writing events successfully
spring.kafka.producer.acks=-1

# Retry if falied
spring.kafka.producer.retries=1

# Check duplicated and correct order events
spring.kafka.producer.properties.[enable.idempotence]=true

# Maximum number of producer's request to write events into broker before waiting acks
spring.kafka.producer.properties.[max.in.flight.requests.per.connection]=5

# MySQL DataSource
spring.datasource.url=${ORDER_DATASOURCE_URL:jdbc:mysql://localhost:3306/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
